int first(unsigned int n);
int second(unsigned int n);
int third (unsigned int n);
int fourth (unsigned int n);
int fifth (unsigned int n,int i);
int sixth (unsigned int n, int i);
int seventh (unsigned int n, int i);
int eighth (unsigned int n);
int ninth(unsigned int n);
int tenth(unsigned int n, int i,int j) ;
int eleventh(unsigned int n,int i);